### ISSUE TITLE
Error: unrecognized archive format

### ISSUE THREAD

**Issue by happysalada** [virtualstaticvoid/asdf-k9s#1]
this is what I get trying to install on macOs 10.14.6
```
Downloading [k9s] from https://github.com/derailed/k9s/releases/download/0.13.6/k9s_0.13.6_Darwin_x86_64.tar.gz to /var/folders/m4/1cnl1mnn6qbcnjr7pyshnfd40000gn/T/asdf_XXXXXXXX.wQF8oanq/k9s_0.13.6_Darwin_x86_64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9    0     9    0     0     27      0 --:--:-- --:--:-- --:--:--    27
Creating bin directory
Cleaning previous binaries
Extracting archive
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
```

am I missing a dependency?

(I verified I have tar)
```
|> which tar
/usr/bin/tar
```

I've been using k9s from brew before, just wanted to get the asdf version

**Comment by virtualstaticvoid** [comment]
Hi @happysalada 

It seems there was a change in tag/version convention in the k9s [releases](https://github.com/derailed/k9s/releases), which caused the download file name to be incorrect.

I've fixed the issue.

**Comment by happysalada** [comment]
When I check list-all, I see
v0.13.6 as the latest version
in my .tool-versions file, I tried both v0.13.6 and 0.13.6 and they both give me that same error.
What version name are you using?

**Comment by virtualstaticvoid** [comment]
Hi @happysalada 

You may need to update the plugin. 

Run `asdf plugin-update k9s` and then check that `list-all` shows the following output.

```
$ asdf list-all k9s
v0.13.6
v0.13.5
v0.13.4
v0.13.3
v0.13.2
v0.13.1
v0.13.0
0.9.3
0.9.2
0.9.1
0.9.0
0.8.4
0.8.3
0.8.2
... truncated
```

You can then install the desired version, using for example `asdf install k9s v0.13.6` and it should work.

**Comment by happysalada** [comment]
I have just done a `asdf plugin update --all`
then 
```
|> asdf install k9s v0.13.6
Downloading [k9s] from https://github.com/derailed/k9s/releases/download/v0.13.6/k9s_v0.13.6_Darwin_x86_64.tar.gz to /var/folders/m4/1cnl1mnn6qbcnjr7pyshnfd40000gn/T/asdf_XXXXXXXX.S2dJKMkP/k9s_v0.13.6_Darwin_x86_64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9    0     9    0     0     22      0 --:--:-- --:--:-- --:--:--    22
Creating bin directory
Cleaning previous binaries
Extracting archive
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
```

am I missing something?
I also tried simply `0.13.6`, I get the same error on both

**Comment by virtualstaticvoid** [comment]
Can you confirm the contents of the `~/.asdf/plugins/k9s/bin/install` script.

The `get_download_url` function should be:

```
get_download_url() {
  local install_type=$1
  local tag=$2
  local version=$2

  # releases after 0.1.12 changed tag/version convention
  # the tag contains "v*" whereas the file download does not
  if [[ "$version" == v* ]]; then
    version=${version:1} # remove leading "v"
  fi

  local platform=$(get_platform)
  local arch=$(get_arch)

  echo "https://github.com/derailed/k9s/releases/download/${tag}/k9s_${version}_${platform}_${arch}.tar.gz"
}
```

Also I checked the [Travis build](https://travis-ci.org/virtualstaticvoid/asdf-k9s/jobs/642278384#L1231) for this version and it is generating the correct URL for the download.

In your log, it appears to still have the old URL, which incorrectly has the "v" in the filename.

```
Downloading [k9s] from https://github.com/derailed/k9s/releases/download/v0.13.6/k9s_v0.13.6_Darwin_x86_64.tar.gz to ...
                                                                                     ^
                                                                                     |
```

**Comment by virtualstaticvoid** [comment]
To be certain, you can try uninstalling and reinstalling the k9s plugin.

**Comment by happysalada** [comment]
just did

after removing and installing this is what I get (just for info)
```
|> asdf plugin add k9s
updating plugin repository...
HEAD is now at fc64423 Merge pull request #181 from sudermanjr/sudermanjr/redskyctl
```

after that when I try to install v0.13.6 I get the same error

**Comment by virtualstaticvoid** [comment]
I think I've figured it out.

When installing, you used `asdf plugin add k9s` which installs the ["well known"](https://github.com/asdf-vm/asdf-plugins/blob/master/plugins/k9s) k9s plugin which is from https://github.com/looztra/asdf-k9s.

Install using `asdf plugin-add k9s https://github.com/virtualstaticvoid/asdf-k9s.git` to use this repository.

**Comment by happysalada** [comment]
Thanks a lot!
Sorry for wasting your time on this.
It's working great!
